### ISSUE TITLE
Casting Quest to PC without Cord

### ISSUE THREAD

**Issue by parkerhams** [parkerhams/grandma-game#79]

**Comment by carpentre1** [comment]
We tried using a hotspot, but got ~1 frame per second because of the amount of bandwidth that's necessary to stream content. This issue will be the same across the board for every wireless method, though maybe some of them compress the data (or have options for lower fidelity casting) before sending it and make it easier to stream at lower bandwidths? I can only imagine that the wifi at the Logan Playtest will be pretty stressed, so this is likely to be just as much of an issue there.
I think in the worst case scenario, we just don't cast; corded casting is too inhibitive of the player experience to be worth it.
